#SPDX-License-Identifier: MIT-0
---
# tasks file for mongodb

- name: Ensure MongoDB data directory exists
  file:
    path: "{{ mongo_data_dir }}"
    state: directory
    mode: '0755'

- name: Pull MongoDB image from Docker Hub
  community.docker.docker_image:
    name: "{{ mongo_image }}"
    tag: "{{ mongo_tag }}"
    source: pull
    state: present

- name: Run MongoDB container with persistent volume and credentials
  community.docker.docker_container:
    name: yolo-mongodb
    image: "{{ mongo_image }}:{{ mongo_tag }}"
    state: started
    restart_policy: always
    published_ports:
      - "{{ mongo_port }}:{{ mongo_port }}"
    volumes:
      - "{{ mongo_data_dir }}:/data/db"
    env:
      MONGO_INITDB_ROOT_USERNAME: "{{ mongo_root_user }}"
      MONGO_INITDB_ROOT_PASSWORD: "{{ mongo_root_password }}"
    networks:
      - name: yolo-net  

