- name: Ensure backend directory exists
  file:
    path: /home/ubuntu/backend
    state: directory
    mode: '0755'

- name: Pull backend image from Docker Hub
  community.docker.docker_image:
    name: vusenad/yolo-backend
    tag: v1.0.1
    source: pull
    state: present

- name: Run backend container
  community.docker.docker_container:
    name: yolo-backend
    image: vusenad/yolo-backend:v1.0.1
    state: started
    restart_policy: always
    published_ports:
      - "5000:5000"
    networks:
      - name: yolo-net  
