- block:
    - name: Update and upgrade system packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install essential utilities
      apt:
        name:
          - curl
          - git
          - vim
          - unzip
          - htop
        state: present

    - name: Ensure app user exists
      user:
        name: "{{ app_user }}"
        state: present
        shell: /bin/bash

    - name: Create project directory
      file:
        path: "{{ project_root }}"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'

    - name: Create shared Docker network for yolo stack
      community.docker.docker_network:
        name: yolo-net
        state: present

  when: ansible_os_family == "Debian"
  tags: ['common', 'setup']
