#SPDX-License-Identifier: MIT-0
---
# tasks file for client

- name: Ensure client directory exists
  file:
    path: /home/ubuntu/client
    state: directory
    mode: '0755'

- name: Pull client image from Docker Hub
  community.docker.docker_image:
    name: vusenad/client
    tag: v1.0.0
    source: pull
    state: present

- name: Run client container
  community.docker.docker_container:
    name: yolo-client
    image: vusenad/client:v1.0.0
    state: started
    restart_policy: always
    published_ports:
      - "80:80"
    networks:
      - name: yolo-net
